# Gradle
# Build your Java projects and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/java

resources:
  containers:
  - container: ubuntu18
    image: ubuntu:18.04

jobs:
  - job: Styleguide
    pool:
      vmImage: 'Ubuntu 16.04'

    container: ubuntu18

    steps:
        - script: |
            apt-get update -y
            apt-get install clang-format python3-setuptools -y
          displayName: 'Install Dependencies'
        - script: |
            wpiformat -y 2018 -clang 5.0
          displayName: 'Run wpiformat'
          failOnStderr: 'true'
        - script: |
            git --no-pager diff --exit-code HEAD  # Ensure formatter made no changes
          displayName: 'Check wpiformat Output'
          failOnStderr: 'true'

  - job: WindowsStyleguide
    pool:
      vmImage: 'vs2017-win2016'

    steps:
      - script: |
          choco install llvm --version 7.0.1
        displayName: 'Install Dependencies'
      - script: |
          cd styleguide\wpiformat
          py -3 setup.py build
          py -3 setup.py install --optimize=1 --skip-build
        displayName: 'Build'
